// MOCK-004: Comprehensive SI Partner Data (20 records)

export type SiPartnerTier = 'diamond' | 'gold' | 'silver';
export type FinancialGrade = 'A+' | 'A' | 'A-' | 'BB+' | 'BB' | 'B+';

export interface SiPartner {
  id: string;
  company_name: string;
  tier: SiPartnerTier;
  registration_number: string;
  region: string;
  city: string;
  founded_year: number;
  employee_count: number;
  capabilities: string[];
  financial_grade: FinancialGrade;
  success_rate: number;
  completed_projects: number;
  failed_projects: number;
  review_count: number;
  avg_rating: number;
  contact_name: string;
  contact_phone: string;
  contact_email: string;
  website?: string;
  created_at: string;
}

export const MOCK_SI_PARTNERS: SiPartner[] = [
  // Diamond Tier (3)
  {
    id: 'si-0001',
    company_name: '로봇시공(주)',
    tier: 'diamond',
    registration_number: '301-81-11111',
    region: '서울특별시',
    city: '강남구',
    founded_year: 2010,
    employee_count: 85,
    capabilities: ['용접', '핸들링', '조립', '검사', '팔레타이징', '도장', '연마'],
    financial_grade: 'A+',
    success_rate: 96.8,
    completed_projects: 187,
    failed_projects: 6,
    review_count: 112,
    avg_rating: 4.8,
    contact_name: '김태수',
    contact_phone: '02-555-1001',
    contact_email: 'contact@robotsigong.kr',
    website: 'https://robotsigong.kr',
    created_at: new Date(Date.now() - 365 * 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'si-0002',
    company_name: '에이스시스템즈',
    tier: 'diamond',
    registration_number: '302-81-22222',
    region: '경기도',
    city: '수원시',
    founded_year: 2012,
    employee_count: 72,
    capabilities: ['용접', '절단', '핸들링', '검사', '포장', 'AGV'],
    financial_grade: 'A+',
    success_rate: 94.2,
    completed_projects: 156,
    failed_projects: 10,
    review_count: 98,
    avg_rating: 4.7,
    contact_name: '이승호',
    contact_phone: '031-555-2002',
    contact_email: 'info@acesystems.co.kr',
    website: 'https://acesystems.co.kr',
    created_at: new Date(Date.now() - 365 * 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'si-0003',
    company_name: '테크인티그레이션',
    tier: 'diamond',
    registration_number: '303-81-33333',
    region: '인천광역시',
    city: '연수구',
    founded_year: 2011,
    employee_count: 68,
    capabilities: ['조립', 'AGV', '팔레타이징', '핸들링', '검사', '포장'],
    financial_grade: 'A',
    success_rate: 95.5,
    completed_projects: 164,
    failed_projects: 8,
    review_count: 105,
    avg_rating: 4.9,
    contact_name: '박진우',
    contact_phone: '032-555-3003',
    contact_email: 'contact@techintegration.kr',
    created_at: new Date(Date.now() - 365 * 4.5 * 24 * 60 * 60 * 1000).toISOString(),
  },

  // Gold Tier (7)
  {
    id: 'si-0004',
    company_name: '스마트오토메이션',
    tier: 'gold',
    registration_number: '304-81-44444',
    region: '경기도',
    city: '성남시',
    founded_year: 2014,
    employee_count: 45,
    capabilities: ['용접', '핸들링', '조립', '검사', '팔레타이징'],
    financial_grade: 'A',
    success_rate: 92.3,
    completed_projects: 104,
    failed_projects: 9,
    review_count: 67,
    avg_rating: 4.6,
    contact_name: '최민지',
    contact_phone: '031-555-4004',
    contact_email: 'info@smartauto.kr',
    created_at: new Date(Date.now() - 365 * 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'si-0005',
    company_name: '프로봇솔루션',
    tier: 'gold',
    registration_number: '305-81-55555',
    region: '서울특별시',
    city: '금천구',
    founded_year: 2015,
    employee_count: 38,
    capabilities: ['핸들링', '팔레타이징', '포장', '검사'],
    financial_grade: 'A-',
    success_rate: 91.7,
    completed_projects: 96,
    failed_projects: 9,
    review_count: 58,
    avg_rating: 4.5,
    contact_name: '정수현',
    contact_phone: '02-555-5005',
    contact_email: 'sales@probotsolution.com',
    created_at: new Date(Date.now() - 365 * 2.8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'si-0006',
    company_name: '(주)디지털로보틱스',
    tier: 'gold',
    registration_number: '306-81-66666',
    region: '부산광역시',
    city: '해운대구',
    founded_year: 2013,
    employee_count: 52,
    capabilities: ['용접', '절단', '연마', '도장', '핸들링'],
    financial_grade: 'A',
    success_rate: 93.8,
    completed_projects: 112,
    failed_projects: 7,
    review_count: 74,
    avg_rating: 4.7,
    contact_name: '강현수',
    contact_phone: '051-555-6006',
    contact_email: 'contact@digitalrobotics.co.kr',
    created_at: new Date(Date.now() - 365 * 3.5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'si-0007',
    company_name: '오토메이션파트너',
    tier: 'gold',
    registration_number: '307-81-77777',
    region: '대구광역시',
    city: '달서구',
    founded_year: 2016,
    employee_count: 33,
    capabilities: ['조립', '검사', '핸들링', 'AGV'],
    financial_grade: 'A-',
    success_rate: 90.5,
    completed_projects: 84,
    failed_projects: 9,
    review_count: 52,
    avg_rating: 4.4,
    contact_name: '윤지혜',
    contact_phone: '053-555-7007',
    contact_email: 'info@autopartner.kr',
    created_at: new Date(Date.now() - 365 * 2.5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'si-0008',
    company_name: '퓨처테크(주)',
    tier: 'gold',
    registration_number: '308-81-88888',
    region: '경기도',
    city: '화성시',
    founded_year: 2015,
    employee_count: 41,
    capabilities: ['팔레타이징', '포장', 'AGV', '핸들링'],
    financial_grade: 'A',
    success_rate: 92.1,
    completed_projects: 101,
    failed_projects: 9,
    review_count: 63,
    avg_rating: 4.6,
    contact_name: '서동현',
    contact_phone: '031-555-8008',
    contact_email: 'sales@futuretech.co.kr',
    created_at: new Date(Date.now() - 365 * 2.6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'si-0009',
    company_name: '로봇엔지니어링',
    tier: 'gold',
    registration_number: '309-81-99999',
    region: '광주광역시',
    city: '북구',
    founded_year: 2014,
    employee_count: 36,
    capabilities: ['용접', '핸들링', '조립', '검사'],
    financial_grade: 'BB+',
    success_rate: 89.8,
    completed_projects: 78,
    failed_projects: 9,
    review_count: 48,
    avg_rating: 4.3,
    contact_name: '임채영',
    contact_phone: '062-555-9009',
    contact_email: 'contact@roboteng.kr',
    created_at: new Date(Date.now() - 365 * 3.2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'si-0010',
    company_name: '넥스트오토(주)',
    tier: 'gold',
    registration_number: '310-81-00001',
    region: '서울특별시',
    city: '구로구',
    founded_year: 2016,
    employee_count: 29,
    capabilities: ['핸들링', '검사', '포장', '팔레타이징'],
    financial_grade: 'A-',
    success_rate: 91.3,
    completed_projects: 92,
    failed_projects: 9,
    review_count: 56,
    avg_rating: 4.5,
    contact_name: '한지수',
    contact_phone: '02-555-0010',
    contact_email: 'info@nextauto.co.kr',
    created_at: new Date(Date.now() - 365 * 2.4 * 24 * 60 * 60 * 1000).toISOString(),
  },

  // Silver Tier (10)
  {
    id: 'si-0011',
    company_name: '(주)신성시스템',
    tier: 'silver',
    registration_number: '311-81-11112',
    region: '경기도',
    city: '안산시',
    founded_year: 2017,
    employee_count: 22,
    capabilities: ['핸들링', '조립', '검사'],
    financial_grade: 'A-',
    success_rate: 88.5,
    completed_projects: 61,
    failed_projects: 8,
    review_count: 38,
    avg_rating: 4.2,
    contact_name: '조민석',
    contact_phone: '031-555-1011',
    contact_email: 'sales@shinsung.kr',
    created_at: new Date(Date.now() - 365 * 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'si-0012',
    company_name: '케이로봇(주)',
    tier: 'silver',
    registration_number: '312-81-22223',
    region: '서울특별시',
    city: '영등포구',
    founded_year: 2018,
    employee_count: 18,
    capabilities: ['팔레타이징', '포장', '핸들링'],
    financial_grade: 'BB+',
    success_rate: 87.2,
    completed_projects: 54,
    failed_projects: 8,
    review_count: 32,
    avg_rating: 4.1,
    contact_name: '김다은',
    contact_phone: '02-555-1012',
    contact_email: 'contact@krobot.co.kr',
    created_at: new Date(Date.now() - 365 * 1.8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'si-0013',
    company_name: '인텔리전스오토',
    tier: 'silver',
    registration_number: '313-81-33334',
    region: '부산광역시',
    city: '강서구',
    founded_year: 2018,
    employee_count: 24,
    capabilities: ['용접', '핸들링', '조립'],
    financial_grade: 'BB+',
    success_rate: 89.3,
    completed_projects: 65,
    failed_projects: 8,
    review_count: 41,
    avg_rating: 4.3,
    contact_name: '이현우',
    contact_phone: '051-555-1013',
    contact_email: 'info@intelligenceauto.com',
    created_at: new Date(Date.now() - 365 * 1.7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'si-0014',
    company_name: '스마트솔루션즈',
    tier: 'silver',
    registration_number: '314-81-44445',
    region: '경기도',
    city: '용인시',
    founded_year: 2019,
    employee_count: 16,
    capabilities: ['검사', '핸들링', '포장'],
    financial_grade: 'BB+',
    success_rate: 86.7,
    completed_projects: 52,
    failed_projects: 8,
    review_count: 29,
    avg_rating: 4.0,
    contact_name: '박서영',
    contact_phone: '031-555-1014',
    contact_email: 'sales@smartsol.kr',
    created_at: new Date(Date.now() - 365 * 1.5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'si-0015',
    company_name: '(주)에이텍',
    tier: 'silver',
    registration_number: '315-81-55556',
    region: '대전광역시',
    city: '유성구',
    founded_year: 2019,
    employee_count: 19,
    capabilities: ['조립', '검사', '핸들링'],
    financial_grade: 'A-',
    success_rate: 88.9,
    completed_projects: 63,
    failed_projects: 8,
    review_count: 36,
    avg_rating: 4.2,
    contact_name: '정우진',
    contact_phone: '042-555-1015',
    contact_email: 'contact@atech.co.kr',
    created_at: new Date(Date.now() - 365 * 1.4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'si-0016',
    company_name: '테크노시스템',
    tier: 'silver',
    registration_number: '316-81-66667',
    region: '경기도',
    city: '평택시',
    founded_year: 2020,
    employee_count: 14,
    capabilities: ['팔레타이징', 'AGV', '핸들링'],
    financial_grade: 'BB',
    success_rate: 85.1,
    completed_projects: 46,
    failed_projects: 8,
    review_count: 25,
    avg_rating: 4.0,
    contact_name: '최수빈',
    contact_phone: '031-555-1016',
    contact_email: 'info@technosystem.kr',
    created_at: new Date(Date.now() - 365 * 1.2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'si-0017',
    company_name: '로보틱스플러스',
    tier: 'silver',
    registration_number: '317-81-77778',
    region: '인천광역시',
    city: '남동구',
    founded_year: 2020,
    employee_count: 21,
    capabilities: ['용접', '핸들링', '검사'],
    financial_grade: 'BB+',
    success_rate: 87.6,
    completed_projects: 57,
    failed_projects: 8,
    review_count: 33,
    avg_rating: 4.1,
    contact_name: '강태현',
    contact_phone: '032-555-1017',
    contact_email: 'sales@roboticsplus.kr',
    created_at: new Date(Date.now() - 365 * 1.1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'si-0018',
    company_name: '퓨전오토메이션',
    tier: 'silver',
    registration_number: '318-81-88889',
    region: '대구광역시',
    city: '수성구',
    founded_year: 2021,
    employee_count: 12,
    capabilities: ['조립', '포장', '핸들링'],
    financial_grade: 'B+',
    success_rate: 84.3,
    completed_projects: 40,
    failed_projects: 7,
    review_count: 22,
    avg_rating: 4.0,
    contact_name: '윤성호',
    contact_phone: '053-555-1018',
    contact_email: 'contact@fusionauto.com',
    created_at: new Date(Date.now() - 365 * 0.9 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'si-0019',
    company_name: '(주)프리미엄로봇',
    tier: 'silver',
    registration_number: '319-81-99990',
    region: '경기도',
    city: '시흥시',
    founded_year: 2021,
    employee_count: 17,
    capabilities: ['핸들링', '검사', '팔레타이징'],
    financial_grade: 'BB+',
    success_rate: 86.2,
    completed_projects: 51,
    failed_projects: 8,
    review_count: 28,
    avg_rating: 4.1,
    contact_name: '서지원',
    contact_phone: '031-555-1019',
    contact_email: 'info@premiumrobot.kr',
    created_at: new Date(Date.now() - 365 * 0.8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'si-0020',
    company_name: '아이로봇시스템',
    tier: 'silver',
    registration_number: '320-81-00002',
    region: '서울특별시',
    city: '송파구',
    founded_year: 2022,
    employee_count: 10,
    capabilities: ['포장', 'AGV', '핸들링'],
    financial_grade: 'BB',
    success_rate: 82.5,
    completed_projects: 33,
    failed_projects: 7,
    review_count: 18,
    avg_rating: 3.9,
    contact_name: '한예린',
    contact_phone: '02-555-1020',
    contact_email: 'sales@irobotsystem.kr',
    created_at: new Date(Date.now() - 365 * 0.6 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export function getSiPartnerById(id: string): SiPartner | undefined {
  return MOCK_SI_PARTNERS.find((si) => si.id === id);
}

export function getSiPartnersByTier(tier: SiPartnerTier): SiPartner[] {
  return MOCK_SI_PARTNERS.filter((si) => si.tier === tier);
}

export function getSiPartnersByRegion(region: string): SiPartner[] {
  return MOCK_SI_PARTNERS.filter((si) => si.region === region);
}

export function getSiPartnersByCapability(capability: string): SiPartner[] {
  return MOCK_SI_PARTNERS.filter((si) =>
    si.capabilities.some((cap) => cap.includes(capability))
  );
}

export function searchSiPartners(query: string): SiPartner[] {
  const lowerQuery = query.toLowerCase();
  return MOCK_SI_PARTNERS.filter(
    (si) =>
      si.company_name.toLowerCase().includes(lowerQuery) ||
      si.capabilities.some((cap) => cap.toLowerCase().includes(lowerQuery)) ||
      si.region.includes(query) ||
      si.city.includes(query)
  );
}
